set(PROJECT_PATH "lib/C")
set(SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/${PROJECT_PATH}")
set(BINARY_DIR "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_PATH}")

ExternalProject_Add(
    C
    SOURCE_DIR "${SOURCE_DIR}"
    BINARY_DIR "${BINARY_DIR}"
    INSTALL_DIR "${EXTERNAL_PROJECT_INSTALL_DIR}"
    CMAKE_CACHE_ARGS
    -DCMAKE_INSTALL_PREFIX:PATH=${EXTERNAL_PROJECT_INSTALL_DIR}
    -DCMAKE_MODULE_PATH:PATH=${CMAKE_CURRENT_SOURCE_DIR}/cmake/modules
    ${EXTERNAL_PROJECT_ARGS})
